### ISSUE TITLE
Using "XonXoff" and "LessArduino" branches - Both button Jogs (+ and -) all move in + direction 

### ISSUE THREAD

**Issue by DougJoseph** [bdring/PendantsForFluidNC#20]
I'm running / testing the "XonXoff" branch of FluidNC and the "LessArduino" branch of FluidDial firmware. 

My FluidDial pendant is set to communicate with the EPS32 / main board on UART2. When I set the baud rate for UART2 to 5000000 (as suggested), I can get the pendant to connect to the EPS32.

In this setup, both the green (+) and red (-) buttons, will cause jogs to happen only in the + direction. It's not a matter of not pausing between + and - (green and red). No matter how long I pause, the red button push jogs in + direction instead of - direction.

**Comment by MitchBradley** [comment]
Fixed

**Comment by DougJoseph** [comment]
Thanks for the fix! 

For anyone still hitting this: It was caused by a minor error in the file named "JoggingScene.cpp." The distance in: 

`onRedButtonPress() 
`

needs to be -2000, not 2000. (It was missing the minus sign).

I edited, recompiled, and now that's working right.

The fix means you should not hit this.
